name: flutter_quran
description: "A Quran Package you can put in your app and it will work without the need for any other resources."
version: 0.1.8
homepage: https://github.com/alheekmahlib/flutter_quran

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  # state management
  get: ^4.6.6


  # local storage
  shared_preferences: ^2.3.2

  #UI
  fluttertoast: ^8.2.8
  flutter_svg: ^2.0.16

  #Tools
  intl: ^0.19.0

# This package supports all platforms listed below.
# But note that it works and fits on mobile size devices
# Additional Screen Sizes will be supported later
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

package_rename_config:
  android:
    package_name: com.alheekmah.quranPackage

  ios:
    bundle_name: com.alheekmah.quranPackage
    package_name: com.alheekmah.quranPackage

  linux:
    package_name: com.alheekmah.quranPackage

  macos:
    package_name: com.alheekmah.quranPackage

flutter:
  assets:
    - lib/assets/
    - lib/assets/fonts/
    - lib/assets/fonts/hafs.ttf
    - lib/assets/jsons/
    - lib/assets/images/
    - lib/assets/svg/
    - lib/assets/svg/surah_name/
    - lib/assets/images/surah_header.png

  fonts:
    - family: hafs
      fonts:
        - asset: packages/flutter_quran/assets/fonts/hafs.ttf

